name: CDK Deploy
on:
  push:
    branch:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          # override: true
      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache
      - name: Setup cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Setup cargo-lambda
        run: cargo binstall -y cargo-lambda
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.4.0"
          cache: "npm"
          cache-dependency-path: "cdk/package-lock.json"
      - name: CDK Deploy
        run: |
          cd cdk
          npm ci
          npx cdk deploy --ci --all --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

